### PR TITLE
feat: block reject event if is_official false PS-161

### PR DESCRIPTION
**Pull request by mikkojamG**
Rejecting events should not be possible if user doesn't have `is_official` property.

https://helsinkisolutionoffice.atlassian.net/browse/PS-161

### CODE REVIEW

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr206-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr206-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr206-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by arpargo — APPROVED** [review]
LGTM

**Pull request merged**
