### PR TITLE
HDS login PS-157

### PR DESCRIPTION
**Pull request by mikkojamG**
https://helsinkisolutionoffice.atlassian.net/browse/PS-157

- Implement HDS login
- Upgrade HDS dependencies to 4.0.0
- Refactoring Javascript files to Typescript files
- Refactoring store to use more modern @reduxjs/toolkit and slices
- Add unit tests to increase test coverage
- Move old e2e Cypress tests to Playwright

Azure changes:
- https://dev.azure.com/City-of-Helsinki/puistotalkoot/_git/puistotalkoot-pipelines/pullrequest/10351

### CODE REVIEW

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]
👍

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://puistotalkoot-pr205-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-UI branch is deployed to platta: https://puistotalkoot-pr205-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
